### ISSUE TITLE
Generate Triangle Collision is not saving on imported mesh

### ISSUE THREAD

**Issue by JamesMWestbrook** [mholtkamp/octave#29]
Linux, Ubuntu 24.04.1 LTS

It sticks when I initially set it to True, but when I close and reopen the project it's back to false, even after saving. 
![Image](https://github.com/user-attachments/assets/ce9948fe-55de-4a03-b39b-7db9320c04e3)
This can be replicated on a brand new project. (Though make sure to create the scene first, otherwise the whole thing freezes if you try to save an imported mesh with no scene open?)

**Comment by mholtkamp** [comment]
I was unable to reproduce this issue on the latest main commit.

How are you saving the static mesh asset? The hotkey to save the selected asset is `Shift + S`. If you hit `Ctrl + S` that will save the current scene.

I think it would be helpful to track unsaved assets with an asterisk next to them, like most software does, so maybe I can add that in the future.

But the fact that the editor crashes when there is no active scene is definitely a bug. Thanks for pointing that out! I just pushed a commit that should fix that issue.

**Comment by mholtkamp** [comment]
Actually, I have only tested on Windows, so it could still be an issue on Linux. You can also save an asset by right clicking on it and selecting "Save". You should see text in the log in the top left saying that the asset has been saved. If you are still seeing the issue where the `Generate Static Mesh` property isn't being saved properly, it could definitely be a Linux issue.

**Comment by JamesMWestbrook** [comment]
(Sorry for late response, never got an email you responded whoops.)

Yep you're right I had to do shift + S to save the asset, not CTR + S which is for the scene. Wasn't aware of that detail till you pointed it out.
As I type this I'm testing on the latest github version if ctr S will still crash when no scene is open and all I have open is the asset, and... Yep the issue seems fixed!
